/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package LCE;

import java.util.ArrayList;
import java.util.List;

import org.eclipse.jgit.api.errors.GitAPIException;
import org.eclipse.jgit.api.errors.InvalidRemoteException;
import org.eclipse.jgit.api.errors.TransportException;
import org.eclipse.jgit.api.errors.JGitInternalException;

public class App {
    public static final String ANSI_RESET = "\u001B[0m";
    public static final String ANSI_BLACK = "\u001B[30m";
    public static final String ANSI_RED = "\u001B[31m";
    public static final String ANSI_GREEN = "\u001B[32m";
    public static final String ANSI_YELLOW = "\u001B[33m";
    public static final String ANSI_BLUE = "\u001B[34m";
    public static final String ANSI_PURPLE = "\u001B[35m";
    public static final String ANSI_CYAN = "\u001B[36m";
    public static final String ANSI_WHITE = "\u001B[37m";
    public static void main(String[] args) {
        App main = new App();
        main.run();
    }

    public void run() {
        Extractor extractor = new Extractor();
        GitLoader gitLoader = new GitLoader();
        System.out.println(ANSI_BLUE + "[debug] > Extractor running...");
        extractor.run();
        System.out.println(ANSI_GREEN + "[debug] > extractor set");
        List<String> result = extractor.extract();
        System.out.println(ANSI_GREEN + "[debug] > extraction done");
        List<String[]> preprocessed = preprocess(result);
        System.out.println(ANSI_GREEN + "[debug] > preprocess success");
        gitLoader.set("D:\\repository_d\\SPI\\core\\LCE\\result", "D:\\repository_d\\SPI\\core\\LCE\\candidates");
        System.out.println(ANSI_BLUE + "[debug] > cleaning result and candidate directory");
        gitLoader.purge();
        System.out.println(ANSI_GREEN + "[debug] > cleaning done");
        System.out.println(ANSI_BLUE+ "[debug] > copying gitignore file to result directory and candidate directory");
        gitLoader.copy("D:\\repository_d\\SPI\\core\\LCE\\gitignore\\.gitignore",
                "D:\\repository_d\\SPI\\core\\LCE\\result\\.gitignore");
        gitLoader.copy("D:\\repository_d\\SPI\\core\\LCE\\gitignore\\.gitignore",
                "D:\\repository_d\\SPI\\core\\LCE\\candidates\\.gitignore");
        System.out.println(ANSI_GREEN + "[debug] > gitignore file copied");
        int counter = 0;
        for (String[] line : preprocessed) {
            gitLoader.count(counter);
            gitLoader.config(line[2], line[0], line[1]);
            gitLoader.run();
            try {
                if(gitLoader.load()) {
                    System.out.println(ANSI_GREEN + "[debug] > gitLoader load success");
                } else {
                    System.out.println(ANSI_RED + "[debug] > gitLoader load failed");
                }
            } catch (Exception e) {
                System.out.println(ANSI_RED + "[error] > Exception :" + e.getMessage());
            }
            counter++;
        }
    }

    private List<String[]> preprocess(List<String> result) {
        List<String[]> result_split = new ArrayList<>();
        try {
            for (String line : result) {
                // System.out.println("[debug] line : " + line);
                String[] line_split = line.split(",");
                String[] selection = new String[] { line_split[0], line_split[2], line_split[4] };
                result_split.add(selection);
            }
        } catch (Exception e) {
            System.out.println("[error] > " + e.getMessage());
        }
        return result_split;
    }

}
