/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package LCE;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test
    void testApp() {
        int[] target = new int[] { 1, 3, 5, 1, 6 };
        int[] tester = new int[] { 1, 5, 3, 1, 4 };
        LCS lcs = new LCS();
        assertArrayEquals(new int[] { 1, 3, 1 }, lcs.LongestCommonSubsequenceofIntegerArray(target, tester));
    }
}
